# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\"\x1f\n\x07sum_req\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x14\n\x07sum_rep\x12\t\n\x01z\x18\x01 \x01(\x05\x32I\n\x03Sum\x12\x1b\n\x03Sum\x12\x08.sum_req\x1a\x08.sum_rep\"\x00\x12%\n\tStreamSum\x12\x08.sum_req\x1a\x08.sum_rep\"\x00(\x01\x30\x01\x62\x06proto3'
)




_SUM_REQ = _descriptor.Descriptor(
  name='sum_req',
  full_name='sum_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='sum_req.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='sum_req.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=48,
)


_SUM_REP = _descriptor.Descriptor(
  name='sum_rep',
  full_name='sum_rep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='z', full_name='sum_rep.z', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['sum_req'] = _SUM_REQ
DESCRIPTOR.message_types_by_name['sum_rep'] = _SUM_REP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sum_req = _reflection.GeneratedProtocolMessageType('sum_req', (_message.Message,), {
  'DESCRIPTOR' : _SUM_REQ,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:sum_req)
  })
_sym_db.RegisterMessage(sum_req)

sum_rep = _reflection.GeneratedProtocolMessageType('sum_rep', (_message.Message,), {
  'DESCRIPTOR' : _SUM_REP,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:sum_rep)
  })
_sym_db.RegisterMessage(sum_rep)



_SUM = _descriptor.ServiceDescriptor(
  name='Sum',
  full_name='Sum',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=72,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sum',
    full_name='Sum.Sum',
    index=0,
    containing_service=None,
    input_type=_SUM_REQ,
    output_type=_SUM_REP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamSum',
    full_name='Sum.StreamSum',
    index=1,
    containing_service=None,
    input_type=_SUM_REQ,
    output_type=_SUM_REP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUM)

DESCRIPTOR.services_by_name['Sum'] = _SUM

# @@protoc_insertion_point(module_scope)
